### ISSUE TITLE
Onnx Converted but gives error on inference

### ISSUE THREAD

**Issue by ghost** [kongyanye/EfficientDet-TensorRT#1]
Hi, I followed the instructions you have given and followed step-by-step to convert the torch2onnx for my custom dataset. The .pth works fine on the inference. However, when I convert it to the .onnx file, I get the following error, while infernece:
Traceback (most recent call last):
  File "C:\Users\Subhan.Khan\AppData\Local\anaconda3\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\Subhan.Khan\AppData\Local\anaconda3\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Subhan.Khan\Python_Code\Tests\EfficientDet\main.py", line 603, in process_video_inference
    orig_frame = draw_boxes_on_image(orig_frame, outputs, frame.shape, fps=fps)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhan.Khan\Python_Code\Tests\EfficientDet\main.py", line 224, in draw_boxes_on_image
    boxes = boxes[selected_indices].astype(np.int32)  # Ensure boxes are integers
            ~~~~~^^^^^^^^^^^^^^^^^^
IndexError: boolean index did not match indexed array along dimension 2; dimension is 4 but corresponding boolean dimension is 1

Any idea?

**Comment by ghost** [comment]
Never mind, I have fixed the issue.
